POST https://pedro.sch.bme.hu/channel
Content-Type: application/json

{
    "channel_name": "cluedo-server-pedro",
    "auth_key": "4452",
    "max_user": 3
}

###

PUT https://pedro.sch.bme.hu/stop-waiting/5f91ef4a66190b5510714ce3

###

GET https://pedro.sch.bme.hu/channel

###

GET https://pedro.sch.bme.hu/channel-by-limit?max_user=4

###

GET https://pedro.sch.bme.hu/channel/5f90a37786feeb4f480f1d6f

###

DELETE https://pedro.sch.bme.hu/channel/5f909d18cbaf662b0cf90fa8

###

DELETE https://pedro.sch.bme.hu/channel/

###

POST https://pedro.sch.bme.hu/player
Content-Type: application/json

{
    "player_name": "Cicus",
    "password": "mizujs"
}

###

PUT https://pedro.sch.bme.hu/login-player
Content-Type: application/json

{
    "player_name": "Lajos",
    "password": "jelszo"
}

###

PUT https://pedro.sch.bme.hu/logout-player
Content-Type: application/json

{
    "player_name": "Cicus",
    "password": "mizujs"
}

###

PUT https://pedro.sch.bme.hu/reset

###

GET https://pedro.sch.bme.hu/player

###

DELETE https://pedro.sch.bme.hu/player/5f909dcacbaf662b0cf90fa9

###

DELETE https://pedro.sch.bme.hu/player/

###

PUT https://pedro.sch.bme.hu/join-channel/5f73bc0a4f0422532c03123e
Content-Type: application/json

{
    "player_name": "Pedro",
    "auth_key": "4452"
}

###

PUT https://pedro.sch.bme.hu/leave-channel/5f91b2d8c9fcfb23d40c4f90?player_name=Cicus