POST https://pedro.sch.bme.hu/channel
Content-Type: application/json

{
    "channel_name": "cluedo-server-pedro",
    "auth_key": "4452",
    "max_user": 5
}

###

GET https://pedro.sch.bme.hu/channel

###

GET https://pedro.sch.bme.hu/channel/5f737224357879281413aa87

###

DELETE https://pedro.sch.bme.hu/channel/5f73b947fd2d925facb00876

###

DELETE https://pedro.sch.bme.hu/channel/

###

POST https://pedro.sch.bme.hu/player
Content-Type: application/json

{
    "player_name": "Cicus",
    "password": "mizujs"
}

###

PUT https://pedro.sch.bme.hu/login-player
Content-Type: application/json

{
    "player_name": "Cicus",
    "password": "mizujs"
}

###

PUT https://pedro.sch.bme.hu/logout-player
Content-Type: application/json

{
    "player_name": "Lajos",
    "password": "jelszo"
}

###

GET https://pedro.sch.bme.hu/player

###

DELETE https://pedro.sch.bme.hu/player/5f8efaa2bad91807a405d08b

###

DELETE https://pedro.sch.bme.hu/player/

###

PUT https://pedro.sch.bme.hu/join-channel/5f73bc0a4f0422532c03123e
Content-Type: application/json

{
    "player_name": "Pedro",
    "auth_key": "4452"
}

###

PUT https://pedro.sch.bme.hu/leave-channel/5f8f2332780f9834c0cb6989?player_name=Pedro