openapi: 3.0.0
info:
  title: Harry Potter Cluedo
  version: '1.0'
  description: This is a REST API for Harry Potter Cluedo mobile application.
  contact:
    name: Orosz Péter
    url: 'https://facebook.com/porosz.eter'
    email: orosz401@gmail.com
servers:
  - url: 'http://localhost:3000'
paths: {}
components:
  schemas:
    Player:
      title: Player
      type: object
      properties:
        id:
          type: integer
        card:
          $ref: '#/components/schemas/PlayerCard'
        pos:
          type: object
          properties:
            row:
              type: integer
            col:
              type: integer
        tile:
          type: integer
        gender:
          type: string
        hp:
          type: number
        mystery_cards:
          type: array
          items:
            $ref: '#/components/schemas/MysteryCard'
        helper_cards:
          type: array
          items:
            $ref: '#/components/schemas/HelperCard'
    MysteryCard:
      title: MysteryCard
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image_res:
          type: integer
        verso:
          type: integer
        tpye:
          type: string
    HelperCard:
      title: HelperCard
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image_res:
          type: integer
        verso:
          type: integer
        type:
          type: string
        count:
          type: integer
        number_of_helping_cases:
          type: integer
    PlayerCard:
      title: PlayerCard
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        image_res:
          type: integer
        verso:
          type: integer
    Suspect:
      title: Suspect
      type: object
      properties:
        id:
          type: integer
          description: ID of player.
        room:
          type: string
        tool:
          type: string
        suspect:
          type: string
  securitySchemes:
    API Key - 1:
      type: oauth2
